---
all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 127.0.0.1
          ansible_port: 2221
        web2:
          ansible_host: 127.0.0.1
          ansible_port: 2222
      vars:
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
        env_name: staging
