apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-lab.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
