apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: handbook-app-secret
  namespace: handbook-lab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: handbook-app-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: handbook/lab/api-key
        property: value
