image: python:3.12-slim

definitions:
  caches:
    pip: ~/.cache/pip

pipelines:
  branches:
    main:
      - step:
          name: Test on main
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - pytest -v
  default:
    - step:
        name: Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pytest -v
