apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hooks-demo.fullname" . }}
  labels:
    {{- include "hooks-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hooks-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hooks-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
